sonar.exclusions=.github/workflows/hexlet-check.yml,**/tasks/index.html


# Подавляем python:S1192 для всех файлов forms.py в проекте
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S1192
sonar.issue.ignore.multicriteria.e1.resourceKey=**/forms.py
