sonar.projectKey=lytic11-web_python-project-52
sonar.organization=lytic11-web

# Исключаем из анализа файлы Hexlet и сгенерированные шаблоны
sonar.exclusions=.github/workflows/hexlet-check.yml,**/tasks/index.html
