sonar.projectKey=lytic11-web_python-project-52
sonar.organization=lytic11-web
sonar.sources=.
sonar.exclusions=**/tests/**,**/migrations/**,**/__pycache__/**,**/.venv/**,**/venv/**,users/tests.py
sonar.tests=users/tests.py,tasks/tests/
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
